rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: master
  isAdminEnforced: false
  requiredStatusCheckContexts:
    - 'cla/google'
    - 'CI (macos-latest, 2.7, --test)'
    - 'CI (ubuntu-latest, 2.5, --test)'
    - 'CI (ubuntu-latest, 2.6, --test)'
    - 'CI (ubuntu-latest, 2.7, --rubocop --build --yard --linkinator)'
    - 'CI (ubuntu-latest, 2.7, --test)'
    - 'CI (ubuntu-latest, 3.0, --test)'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: yoshi-admins
    permission: admin
  - team: yoshi-ruby-admins
    permission: admin
  - team: yoshi-ruby
    permission: push
