environment:
  matrix:
    - RUBY_VERSION: 23-x64
    - RUBY_VERSION: 22-x64
    - RUBY_VERSION: 21-x64
    - RUBY_VERSION: 200-x64

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - C:\Ruby21\DevKit\devkitvars.bat
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake appveyor:build

notifications:
  - provider: Slack
    auth_token:
      secure: 9YGsB9d3wrST/m6Ep87bIQf+Y7i874+swA51IsTSn7GN0JkNo34tFy9vRTq/921h3cffqNnO8VAnvj41gqXH+iFXz4FNxxvBciWcOW37C8E=
    channel: gcloud
