language: ruby
os:
- osx
osx_image: xcode8.2
rvm:
- 2.4.0
- 2.3.1
- 2.2.5
- 2.1.9
- 2.0.0-p648
script:
- gem install bundler
- bundle exec rake travis:build
notifications:
  slack:
    secure: Ksji5MDNOWnuzuyu9Hblbxse6kGLdH4kXyYkF98C+wawIGLSONWWkuA65wpdqSLtBN/79RCLMWoBzKAGX4xy9BL6Rxb3rLjAMT+FVur6II2yaApzyJ0dmTVeTXnkchPcrO27FK5taPb0Ghr86DUiG3OViY/q1N0AVALDYce5tfE=
