version: 2

jobs:
  release:
    working_directory: ~/googleapis/google-cloud-ruby
    shell: /bin/bash --login -eo pipefail
    docker:
    - image: circleci/ruby:2.5.1-stretch
    steps:
    - checkout
    - run:
        name: Install bundle
        command: gem update --system && gem install bundler && bundle update
    - run: bundle exec rake circleci:release

workflows:
  version: 2

  tests:
    jobs:
      - test-ruby-2.5: &test-filters
          filters:
            branches:
              ignore:
                - gh-pages
                - gcloud-jsondoc
                - gcloud-rdoc
                - yard-gcloud
      - test-ruby-2.4:
          <<: *test-filters
      - test-ruby-2.3:
          <<: *test-filters

  post-build:
    jobs:
      - post:
          filters:
            branches:
              only: master

  gem-release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\S+\/v\S+/

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=VdG8EataF3PrWBZOBH7Hr80BXUjYRLh7o
