# This workflow runs the Bigtable Conformance Test suite against the Bigtable
# client library.
# See https://github.com/googleapis/cloud-bigtable-clients-test
on:
  push:
    branches:
    - main
    paths:
      - 'google-cloud-bigtable/**'
  pull_request:
    paths:
      - 'google-cloud-bigtable/**'
name: conformance
jobs:
  bigtable_conformance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: [
          '3.1',
          '3.2',
          '3.3',
          '3.4',
        ]
    steps:
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.23.0'
    - name: Install tools
      run: "gem install --no-document toys"
    - name: Install dependencies
      run: "cd google-cloud-bigtable/conformance/test_proxy && bundle install"
    - name: Run tests
      run: "cd google-cloud-bigtable && toys conformance test -v"
