name: release-please-label
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
jobs:
  release-please-label:
    if: "${{ github.event.sender.login == 'yoshi-code-bot' && startsWith(github.event.pull_request.title, 'chore: release ') }}"
    runs-on: ubuntu-latest
    steps:
      - name: ReleaseLabel
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.YOSHI_APPROVER_TOKEN}}
          script: |
            core.info('Labeling release');
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['autorelease: pending']
            });
            core.info('Labeled');
