name: Release-Please
on:
  schedule:
    - cron: '47 7 * * *'
  workflow_dispatch:
    inputs:
      gem:
        description: "Name of single gem to release. Leave blank to check all gems."
        required: false
      retries:
        description: "Number of retries, 0 for no retry, or leave blank for the default of 1."
        required: false

jobs:
  release-please:
    if: ${{ github.repository == 'googleapis/google-cloud-ruby' && (!secrets.DISABLE_RELEASE_PLEASE || github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: Install NodeJS 12.x
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Install tools
        run: "gem install --no-document toys && npm install release-please"
      - name: execute
        run: "toys release-please --fork --retry=${{ github.event.inputs.retries }} ${{ github.event.inputs.gem }}"
